


Alter table SERVICEREQUEST
ADD CONSTRAINT CUS_SR_FK FOREIGN KEY(CustomerId) REFERENCES CUSTOMER(CustomerId) ON DELETE SET NULL;
Alter table SERVICEREQUEST
ADD CONSTRAINT DRI_SR_FK FOREIGN KEY(DriverId) REFERENCES DRIVER(DriverId) ON DELETE SET NULL;

Alter table CAB3
ADD CONSTRAINT CAB_CAB3_FK FOREIGN KEY(LicensePlate) REFERENCES CAB(LicensePlate) ON DELETE SET NULL;

Alter table PAYMENT
ADD CONSTRAINT SR_PAYMENT_FK FOREIGN KEY(SRId) REFERENCES SERVICEREQUEST(SRId) ON DELETE SET NULL;

Alter table PAYMENT3
ADD CONSTRAINT PAYMENT_PAYMENT3_FK FOREIGN KEY(PAYMENT_TYPE) REFERENCES PAYMENT(PAYMENT_TYPE) ON DELETE SET NULL;

Alter table ZONE1
ADD CONSTRAINT ZONE_ZONE1_FK FOREIGN KEY(ZONE_ID) REFERENCES ZONE(ZONE_ID) ON DELETE SET NULL;

Alter table PRESENT_IN
ADD CONSTRAINT ZONE_PRESENT_IN_FK FOREIGN KEY(ZONE_ID) REFERENCES ZONE(ZONE_ID) ON DELETE SET NULL;

Alter table PEAK_TIME3
ADD CONSTRAINT PEAK_PEAK3_FK FOREIGN KEY(NUMBER_OF_REQUESTS) REFERENCES PEAK_TIME(NUMBER_OF_REQUESTS) ON DELETE SET NULL;


Alter table ZONE_PEAKTIME_DECIDER
ADD CONSTRAINT ZONE_DECIDER_FK FOREIGN KEY(ZONE_ID) REFERENCES ZONE(ZONE_ID) ON DELETE SET NULL;


Alter table ZONE_PEAKTIME_DECIDER
ADD CONSTRAINT PEAKTIME_DECIDER_FK FOREIGN KEY(PEAKTIME_ID) REFERENCES PEAK_TIME(PEAKTIME_ID) ON DELETE SET NULL;



